name: Image Builds

on:
  push:
  schedule:
    # 2:30am UTC every Sunday, has no particular meaning
    - cron: '30 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - debian-base
          - ftl-build_aarch64
          - ftl-build_arm
          - ftl-build_arm-qemu
          - ftl-build_armhf
          - ftl-build_x86_32
          - ftl-build_x86_64
          - ftl-build_x86_64-musl
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Images
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker-compose pull ${{ matrix.image }}
          docker-compose build --pull ${{ matrix.image }}

      #- name: Docker login
      #  run: sudo docker login --username=${{ secrets.DOCKERHUB_USER }} --password=${{ secrets.DOCKERHUB_PASS }}

      #- name: Tag and push all images
      #  run: ./tag-and-push.sh
