name: Image Builds
env:
  HUB_NAMESPACE: pihole
  #JOB_ID: ${{env.job.id}}
on:
  pull_request:
  push:
  schedule:
    # 2:30am UTC every Sunday, has no particular meaning
    - cron: '30 2 * * 0'

jobs:
  debian-base: &job_template
    runs-on: ubuntu-latest
    steps:
      - name: echo env vars
        run: printenv
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Enable QEMU
        if: contains(env.IMAGE}, 'qemu')
        run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - name: Build Images
        run: |
          echo "Building $IMAGE"
          cd "${BASEDIR:-.}/${CIRCLE_JOB}"
          docker build --pull -t ${IMAGE} .
      - name: Tag and push all images
        if: github.event_name != 'pull_request'
        run: |
          docker login --username=${{ secrets.DOCKERHUB_USER }} --password=${{ secrets.DOCKERHUB_PASS }}
          ./tag-and-push.sh ${IMAGE}
    env:
      IMAGE: debian-base:latest

  arm:
    <<: *job_template
    env:
      BASEDIR: ftl-build
      IMAGE: ftl-build

  arm-qemu:
    <<: *job_template
    env:
      BASEDIR: ftl-build
      IMAGE: ftl-build

  armhf:
    <<: *job_template
    env:
      BASEDIR: ftl-build
      IMAGE: ftl-build

  aarch64:
    <<: *job_template
    env:
      BASEDIR: ftl-build
      IMAGE: ftl-build

  x86_64:
    <<: *job_template
    env:
      BASEDIR: ftl-build
      IMAGE: ftl-build

  x86_64-musl:
    <<: *job_template
    env:
      BASEDIR: ftl-build
      IMAGE: ftl-build

  x86_32:
    <<: *job_template
    env:
      BASEDIR: ftl-build
      IMAGE: ftl-build
